language: python
cache: pip
sudo: false

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27-django111
    - python: "3.6"
      env: TOX_ENV=py36-django111
    - python: "3.6"
      env: TOX_ENV=py36-django20
    - python: "3.6"
      env: TOX_ENV=py36-django21
    - python: "3.6"
      env: TOX_ENV=py36-django22
    - python: "3.7"
      env: TOX_ENV=py37-django111
    - python: "3.7"
      env: TOX_ENV=py37-django20
    - python: "3.7"
      env: TOX_ENV=py37-django21
    - python: "3.7"
      env: TOX_ENV=py37-django22
    - python: "3.8"
      env: TOX_ENV=py38-django111
    - python: "3.8"
      env: TOX_ENV=py38-django20
    - python: "3.8"
      env: TOX_ENV=py38-django21
    - python: "3.8"
      env: TOX_ENV=py38-django22

install: pip install codacy-coverage coverage tox-travis
before_script:
  coverage erase
script:
  tox
after_success:
  coverage combine &&
  coverage report &&
  coverage xml -o coverage/xml/coverage.xml &&
  coverage html --directory=coverage/html &&
  python-codacy-coverage -r coverage/xml/coverage.xml
