dist: xenial
language: python
cache: pip

jobs:
  fast_finish: true
  include:
    - name: "Python 2.7 with django 1.11"
      python: "2.7"
      env: TOX_ENV=py27-django111
    - name: "Python 3.6 with django 1.11"
      python: "3.6"
      env: TOX_ENV=py36-django111
    - name: "Python 3.6 with django 2.0s"
      python:  "3.6"
      env: TOX_ENV=py36-django20
    - name: "Python 3.6 with django 2.1"
      python:  "3.6"
      env: TOX_ENV=py36-django21
    - name: "Python 3.6 with django 2.2"
      python:  "3.6"
      env: TOX_ENV=py36-django22
    - name: "Python 3.7 with django 1.11"
      python:  "3.7"
      env: TOX_ENV=py37-django111
    - name: "Python 3.7 with django 2.0"
      python:  "3.7"
      env: TOX_ENV=py37-django20
    - name: "Python 3.7 with django 2.1"
      python:  "3.7"
      env: TOX_ENV=py37-django21
    - name: "Python 3.7 with django 2.2"
      python:  "3.7"
      env: TOX_ENV=py37-django22
    - name: "Python 3.8 with django 1.11"
      python:  "3.8"
      env: TOX_ENV=py38-django111
    - name: "Python 3.8 with django 2.0"
      python:  "3.8"
      env: TOX_ENV=py38-django20
    - name: "Python 3.8 with django 2.1"
      python:  "3.8"
      env: TOX_ENV=py38-django21
    - name: "Python 3.8 with django 2.2"
      python:  "3.8"
      env: TOX_ENV=py38-django22

install: pip install codacy-coverage coverage tox-travis

before_script:
  coverage erase

script:
  tox

after_success:
  coverage combine &&
  coverage report &&
  coverage xml -o coverage/xml/coverage.xml &&
  coverage html --directory=coverage/html &&
  python-codacy-coverage -r coverage/xml/coverage.xml
